# ~~ Generated by projen. To modify, edit .projenrc.py and run "npx projen".

import json
from setuptools import setup

kwargs = json.loads(
    """
{
    "name": "promptconsole",
    "python_requires": ">=3.8",
    "author": "PromptConsole Team",
    "author_email": "team@promptconsole.dev",
    "version": "0.1.0",
    "description": "A comprehensive prompt management and execution tool",
    "license": "MIT"
}
"""
)

setup(**kwargs)
